# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 600fbf6332d3e036e6c037a0fa09c1aa49902a2f4f4fa699b073f40475be9b0ce5d59c20ed1a5aafa1a6b7fb776687c6f3a382191f3b5e64d35b936a7bdaa044

test:
  secret_key_base: d581c6886d182f6234ee9683a6fa100e5a4fbd97e682f1fe81684198d78324e9be06150f7acc77b9612cb25a0bc253781f9ca22edbbb02c5aaf3a246d6146e10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
